

demo:
    log:
        node: 0
#        path: /data/logs/java/dubbo/demo/
        path: /data/logs/java/dubbo/demo/simpleServer/stress/${demo.log.node}/

dubbo:
    application:
        name: dubbo-springboot-demo-provider-${demo.log.node}
    protocol:
        port: ${linux.port}
